### PR TITLE
restructure of css and html

### PR DESCRIPTION
**Pull request by Moonstone07**
added classes for styling
added header in base
changed the search bar to the menu
styled the tags and the menu a little

### CODE REVIEW

**Comment by Moonstone07** [comment]
added the clear all tags button

**Review by NIMUchanco — CHANGES_REQUESTED** [review]
Your code has <button type="button" id="clearTagsBtn">Clear All Tags</button> inside of id="sortForm" (in the line 24) in home.html.
But it should be inside of id="filterForm".

**Comment by Moonstone07** [comment]
change to code done

**Review by NIMUchanco — APPROVED** [review]
Approved

**Pull request merged**
